name: 'Build Function'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode'
      - 'azurite'
      - '.gitignore'
      - '*.md'

jobs:
  azure:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    env:
      location: 'westeurope'

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy Azure Resources'
      working-directory: DevOps
      run: |
        az deployment group create \
            --resource-group heroapi-dev \
            --name Deployment-dev-$(date +"%Y-%m-%dT%H-%M-%S") \
            --template-file infrastructure.bicep \
            --parameters \
                stage=dev \
                pipResourceGroup=${{ env.publicIpResourceGroup }} \
                adminPrincipalId=${{ needs.init.outputs.devUserGroup }}

  build:
    runs-on: ubuntu-latest
    needs: 
    - azure

    env:
      dotnet-version: '6.0.x'

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup .NET SDK ${{ env.dotnet-version }}'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: 'Restore dependencies'
      run: dotnet restore

    - name: 'Build'
      run: dotnet build --configuration ${{ needs.init.outputs.configuration }}

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Install Azure Function Tools'
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4

    - name: 'Publish'
      working-directory: HeroApi
      run: func azure functionapp publish func-4oppsuzf5z3zy
